/**
 * Scaffold a Catalyst-based custom UI kit project shell.
 *
 * Does NOT include Catalyst component source (licensed zip only).
 * Generates setup, Link integration, theme tokens, color maps, and a
 * components barrel that re-exports from paths you fill from the zip.
 */
import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";
import {
  CATALYST_BADGE_COLORS,
  CATALYST_COMPONENTS,
  CATALYST_CONTROL_COLORS,
  CATALYST_DOWNLOAD_URL,
  CATALYST_DOCS_BASE,
  CATALYST_LINK_SNIPPETS,
  CATALYST_SETUP_STEPS,
  listCatalystCustomizations,
  type CatalystLang,
  type CatalystRouter,
} from "../data/catalyst.ts";

export interface GenerateUiKitOptions {
  /** Output directory (created if missing) */
  outDir: string;
  /** Project display name */
  name?: string;
  lang?: CatalystLang;
  router?: CatalystRouter;
  /** Include Inter @theme CSS */
  interFont?: boolean;
  /** Install heroicons in package.json */
  heroicons?: boolean;
  /** Brand color name mapped onto Tailwind primary (docs-safe theming) */
  brandColor?: string;
  /** Extra solid colors to document in theme map */
  accentColors?: string[];
  componentsDir?: string;
  force?: boolean;
}

export interface GenerateUiKitResult {
  outDir: string;
  filesWritten: string[];
  nextSteps: string[];
  customizations: ReturnType<typeof listCatalystCustomizations>;
}

function write(path: string, content: string, written: string[]) {
  mkdirSync(join(path, ".."), { recursive: true });
  writeFileSync(path, content);
  written.push(path);
}

export function generateCatalystUiKit(opts: GenerateUiKitOptions): GenerateUiKitResult {
  const outDir = resolve(opts.outDir);
  const name = opts.name || "my-ui-kit";
  const lang = opts.lang || "typescript";
  const router = opts.router || "next";
  const ext = lang === "typescript" ? "tsx" : "jsx";
  const cssExt = "css";
  const componentsDir = opts.componentsDir || "src/components";
  const interFont = opts.interFont !== false;
  const heroicons = opts.heroicons !== false;
  const brandColor = opts.brandColor || "indigo";
  const written: string[] = [];

  if (existsSync(outDir) && !opts.force) {
    // allow non-empty if force not set — still write into it
  }
  mkdirSync(outDir, { recursive: true });

  const deps: Record<string, string> = {
    react: "^19.0.0",
    "react-dom": "^19.0.0",
    "@headlessui/react": "^2.2.0",
    motion: "^12.0.0",
    clsx: "^2.1.1",
    tailwindcss: "^4.0.0",
  };
  if (heroicons) deps["@heroicons/react"] = "^2.2.0";
  if (router === "next") deps["next"] = "^15.0.0";
  if (router === "remix") deps["@remix-run/react"] = "^2.15.0";
  if (router === "inertia") deps["@inertiajs/react"] = "^2.0.0";

  write(
    join(outDir, "package.json"),
    JSON.stringify(
      {
        name,
        private: true,
        type: "module",
        scripts: {
          "postinstall:note": "echo Copy Catalyst components from your licensed zip into " + componentsDir,
        },
        dependencies: deps,
      },
      null,
      2
    ) + "\n",
    written
  );

  // Theme CSS — Inter + brand primary mapping (Tailwind v4 @theme)
  const themeCss = `/* Generated by Tailwind Plus MCP (Unofficial) — Catalyst theming scaffold */
/* Docs: Catalyst relies on Tailwind defaults; extend carefully. */

${interFont ? `@import url("https://rsms.me/inter/inter.css");\n` : ""}@import "tailwindcss";

@theme {
${interFont ? `  --font-sans: Inter, ui-sans-serif, system-ui, sans-serif;\n  --font-sans--font-feature-settings: "cv11";\n` : ""}\
  /* Map brand primary onto a default palette stop Catalyst already uses */
  --color-brand-50: var(--color-${brandColor}-50);
  --color-brand-100: var(--color-${brandColor}-100);
  --color-brand-200: var(--color-${brandColor}-200);
  --color-brand-300: var(--color-${brandColor}-300);
  --color-brand-400: var(--color-${brandColor}-400);
  --color-brand-500: var(--color-${brandColor}-500);
  --color-brand-600: var(--color-${brandColor}-600);
  --color-brand-700: var(--color-${brandColor}-700);
  --color-brand-800: var(--color-${brandColor}-800);
  --color-brand-900: var(--color-${brandColor}-900);
  --color-brand-950: var(--color-${brandColor}-950);
}
`;
  write(join(outDir, `src/styles/theme.${cssExt}`), themeCss, written);

  // Color / customization reference for agents
  const themeTs = `/**
 * Catalyst color & customization map (from public docs).
 * Prefer these props over ad-hoc className color overrides.
 */
export const controlColors = ${JSON.stringify(CATALYST_CONTROL_COLORS, null, 2)} as const;

export const badgeColors = ${JSON.stringify(CATALYST_BADGE_COLORS, null, 2)} as const;

export const defaultControlColor = "dark/zinc" as const;
export const defaultBadgeColor = "zinc" as const;

export const buttonStyles = ["solid", "outline", "plain"] as const;

export const brandColor = ${JSON.stringify(brandColor)};

/** Example: <Button color="cyan"> — full list is controlColors */
export type ControlColor = (typeof controlColors)[number];
export type BadgeColor = (typeof badgeColors)[number];

export const classNamePolicy =
  "Only layout utilities (max-w-*, flex, gap). Do not fight component color classes.";

export const iconPolicy = {
  default: "@heroicons/react/16/solid",
  navbarSidebar: "@heroicons/react/20/solid",
  customAttr: 'data-slot="icon"',
};
`;
  write(
    join(outDir, lang === "typescript" ? "src/theme/catalyst-theme.ts" : "src/theme/catalyst-theme.js"),
    themeTs,
    written
  );

  // Link component
  const link = CATALYST_LINK_SNIPPETS[router];
  write(join(outDir, `${componentsDir}/link.${ext}`), link.content, written);

  // Barrel that re-exports expected Catalyst files (user copies from zip)
  const exportLines = CATALYST_COMPONENTS.map((c) => {
    const names = c.exports.join(", ");
    return `export { ${names} } from "./${c.file}";`;
  });
  write(
    join(outDir, `${componentsDir}/index.${lang === "typescript" ? "ts" : "js"}`),
    `/**
 * Re-exports for Catalyst components.
 * After downloading ${CATALYST_DOWNLOAD_URL}
 * copy the ${lang} component files into this directory, then these exports resolve.
 */
${exportLines.join("\n")}
export { Link } from "./link";
`,
    written
  );

  // Placeholder stubs so TypeScript project can typecheck recipes before zip copy
  for (const c of CATALYST_COMPONENTS) {
    const stubPath = join(outDir, `${componentsDir}/${c.file}.${ext}`);
    if (existsSync(stubPath) && !opts.force) continue;
    const exportStubs = c.exports
      .map(
        (e) =>
          `export function ${e}(props: Record<string, unknown>) {\n  throw new Error("Replace stub: copy ${c.file} from catalyst-ui-kit.zip (${lang}). See ${c.docsUrl}");\n}\n`
      )
      .join("\n");
    write(
      stubPath,
      `/** STUB — replace with licensed Catalyst source from zip (${c.file}) */\n${exportStubs}`,
      written
    );
  }

  write(
    join(outDir, `src/recipes/button-colors.${ext}`),
    `import { Button } from "../components/button";

/**
 * Docs: use color prop — full list in src/theme/catalyst-theme
 * @see ${CATALYST_DOCS_BASE}/button
 */
export function ButtonColorGallery() {
  return (
    <div className="flex flex-wrap gap-3">
      <Button color="dark/zinc">Default adaptive</Button>
      <Button color="cyan">Cyan solid</Button>
      <Button outline>Outline</Button>
      <Button plain>Plain</Button>
    </div>
  );
}
`,
    written
  );

  // Fix recipes paths properly
  write(
    join(outDir, `src/recipes/README.md`),
    `# Recipes

These examples mirror public Catalyst docs. Import real components after you copy the zip.

- Buttons: color / outline / plain — ${CATALYST_DOCS_BASE}/button
- Badges: 18 colors — ${CATALYST_DOCS_BASE}/badge
- Forms: invalid, disabled, Field composition — fieldset/input/select
- Layouts: SidebarLayout, StackedLayout, AuthLayout
- Icons: 16/solid default; NavbarItem/SidebarItem use 20/solid; custom icons need data-slot="icon"
`,
    written
  );

  write(
    join(outDir, "CATALYST_SETUP.md"),
    `# ${name} — Catalyst UI Kit setup

Generated by **Tailwind Plus MCP (Unofficial)** from the public Catalyst docs.

## License note

Component **source** is not included. Download with your Tailwind Plus account:

${CATALYST_DOWNLOAD_URL}

Copy the \`${lang}\` files from \`catalyst-ui-kit.zip\` into \`${componentsDir}/\`, replacing the STUB files.

## Checklist (docs coverage)

${CATALYST_SETUP_STEPS.map((s, i) => `${i + 1}. **${s.title}**${s.required ? " (required)" : " (optional)"}\n   ${s.description}${s.commands ? "\n   \`" + s.commands.join("` / `") + "\`" : ""}`).join("\n\n")}

## Router

Link component generated for: **${router}** (\`${componentsDir}/link.${ext}\`)

## Theming

- Control colors (Button, Checkbox, Switch, Radio, DropdownButton): \`${CATALYST_CONTROL_COLORS.length}\` values — see \`src/theme/catalyst-theme\`
- Badge colors: \`${CATALYST_BADGE_COLORS.length}\` values
- Brand mapping: primary → \`${brandColor}\` via CSS variables in \`src/styles/theme.css\`
- Inter font: ${interFont ? "enabled in @theme" : "disabled"}
- className: layout only (docs sharp-knife rule)

## Components (${CATALYST_COMPONENTS.length})

${CATALYST_COMPONENTS.map((c) => `- [${c.name}](${c.docsUrl}) — \`${c.exports.join("`, `")}\``).join("\n")}

## Demo

${"https://catalyst-demo.tailwindui.com"}
`,
    written
  );

  write(
    join(outDir, "README.md"),
    `# ${name}

Custom UI kit project scaffolded for **Catalyst** (Tailwind Plus UI Kit).

\`\`\`bash
# 1. Install deps
npm install

# 2. Download Catalyst (licensed)
open ${CATALYST_DOWNLOAD_URL}

# 3. Copy ${lang} components into ${componentsDir}/

# 4. Import theme CSS in your app entry
# import "./src/styles/theme.css"
\`\`\`

See **CATALYST_SETUP.md** for full docs-aligned customization coverage.
`,
    written
  );

  // Machine-readable manifest for the MCP / agents
  write(
    join(outDir, "catalyst-manifest.json"),
    JSON.stringify(
      {
        generatedBy: "tailwind-plus-mcp",
        name,
        lang,
        router,
        brandColor,
        componentsDir,
        customizations: listCatalystCustomizations(),
        components: CATALYST_COMPONENTS.map((c) => ({
          slug: c.slug,
          file: c.file,
          exports: c.exports,
          colors: c.colors,
          docsUrl: c.docsUrl,
        })),
      },
      null,
      2
    ) + "\n",
    written
  );

  return {
    outDir,
    filesWritten: written,
    nextSteps: [
      `cd ${outDir} && npm install`,
      `Download Catalyst zip: ${CATALYST_DOWNLOAD_URL}`,
      `Copy ${lang} components into ${componentsDir}/ (replace STUB files)`,
      `Import src/styles/theme.css in your app`,
      `Use color props from src/theme/catalyst-theme instead of one-off class colors`,
      `Read CATALYST_SETUP.md for full customization checklist`,
    ],
    customizations: listCatalystCustomizations(),
  };
}
